#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#         :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'git', '~> 4.6.0'
cookbook 'rvm', '~> 0.9.4'
cookbook 'postgresql', '~> 4.0.6'
cookbook 'nodejs', '~> 2.4.4'